//! Implements utility parameter components.

use std::collections::BTreeMap;

use crate::components::{Component, ComponentResult};
use crate::graph::node::MetaMap;
use crate::graph::value::Value;

/// Defines a component's registration information.
pub struct Registration<T> {
    /// The component's kind.
    pub kind: T,
    /// A list of GUIDs that identify the component.
    pub guids: &'static [&'static str],
    /// A list of names and nicknames for the component.
    pub names: &'static [&'static str],
}

impl<T: Copy> Registration<T> {
    /// Creates a new `Registration` instance.
    pub const fn new(kind: T, guids: &'static [&'static str], names: &'static [&'static str]) -> Self {
        Self { kind, guids, names }
    }
}

// --- ComponentKind Enum ---
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ComponentKind {
    Relay,
}

impl ComponentKind {
    pub fn evaluate(self, inputs: &[Value], meta: &MetaMap) -> ComponentResult {
        match self {
            Self::Relay => RelayComponent.evaluate(inputs, meta),
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::Relay => "Relay",
        }
    }
}

// --- Relay Component ---

#[derive(Debug, Default, Clone, Copy)]
struct RelayComponent;

impl Component for RelayComponent {
    fn evaluate(&self, inputs: &[Value], _meta: &MetaMap) -> ComponentResult {
        let mut outputs = BTreeMap::new();

        if inputs.is_empty() {
             outputs.insert("out0".to_string(), Value::Null);
        }

        if let Some(val) = inputs.get(0) {
             // Pass through the first input to likely output names.
             // We output to multiple common keys because the specific output pin name
             // generated by the parser for a Relay component can vary (e.g. "out0", "Output")
             // or might be based on nicknames that are often empty for Relays.
             outputs.insert("Output".to_string(), val.clone());
             outputs.insert("out0".to_string(), val.clone());
             outputs.insert("Relay".to_string(), val.clone());
             outputs.insert("Geometry".to_string(), val.clone());
        }

        Ok(outputs)
    }
}

// --- Registrations ---
pub const RELAY_GUID: &str = "b6236720-8d88-4289-93c3-ac4c99f9b97b";

pub const REGISTRATIONS: &[Registration<ComponentKind>] = &[
    Registration::new(ComponentKind::Relay, &[RELAY_GUID], &["Relay"]),
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::node::MetaMap;

    #[test]
    fn test_relay_component() {
        let component = RelayComponent;
        let val = Value::Text("test".to_string());
        let inputs = vec![val.clone()];
        let outputs = component.evaluate(&inputs, &MetaMap::new()).unwrap();

        // Check that we get the value back on expected outputs
        assert_eq!(outputs.get("Output"), Some(&val));
        assert_eq!(outputs.get("out0"), Some(&val));
    }
}
